# Generated by Django 3.2 on 2023-08-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20230804_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='tipo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
