# Generated by Django 3.2 on 2023-08-06 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_moneda_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezasrepuesto',
            name='tipo_moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.moneda'),
        ),
    ]
